Project/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('secret/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('vendor/', include('vendor.urls')),
    path('customer/', include('customers.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('order/', include('order.urls')),
    path('review/', include('review.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

blog/urls.py
from django.urls import path
from . views import blog_post_view, blog_details_view, create_comment_view, blog_search_view

app_name = 'blog'

urlpatterns = [
    path('', blog_post_view, name='blog_view'),
    path('<slug:slug>', blog_details_view, name='blog_detail'),
    path('<slug:slug>/', create_comment_view, name='create_comment'),
    path('search/', blog_search_view, name='search'),
    # path('<slug:slug>/<int:pk>/delete', comment_delete_view, name='comment_delete'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_list, name='cart_list'),
]

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('checkout', views.checkout, name='checkout'),
    path('confirmation', views.order_complete, name='order_complete'),
    path('returns', views.customerReturns, name='customer_returns'),
    path('cancellation', views.customerCancellations, name='customer_cancellation'),
    path('history', views.customerOrderHistory, name='customer_order_history'),
    path('view/<int:order_id>', views.order_details, name='order_details'),
]

cart/views.py
from django.shortcuts import redirect, render

from .cart import Cart


def cart_list(request):
    cart = Cart(request)

    remove_from_cart = request.GET.get('remove_from_cart')
    change_quantity = request.GET.get('change_quantity')
    quantity = request.GET.get('quantity', 0)

    if remove_from_cart:
        cart.remove(remove_from_cart)
        return redirect('cart:cart_list')

    if change_quantity:
        cart.add(change_quantity, quantity, True)
        return redirect('cart:cart_list')

    return render(request, 'cart/cart.html')

cart/templates/cart/cart.html
{% extends 'core/_base.html' %}
{% block title %}Cart {% endblock %}
{% load static %}
{% block body %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
<!-- slider Area Start-->
<div class="slider-area ">
  <!-- Mobile Menu -->
  <div class="single-slider slider-height2 d-flex align-items-center" data-background="{% static 'assets/img/hero/category.jpg' %}">
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="hero-cap text-center">
            <h2>Card List</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- slider Area End-->
<!--================Cart Area =================-->
    {% if cart %}
        <div class="container pt-4 mb-5">
        <div class="box mb-6">
            <div class="table">
                <table class="table is-fullwidth is-striped">
                    <thead>
                        <th></th>
                        <th>Product</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th></th>
                    </thead>

                    <tbody>
                        {% for item in cart %}
                            <tr>
                                <td>
                                    {% if item.product.image %}
                                    <figure class="image is-64x64">
                                        <img src="{{ item.product.image.url }}">
                                    </figure>
                                    {% else %}
                                    <figure class="image is-64x64">
                                        <img src="{{ item.product.url }}">
                                    </figure>
                                    {% endif %}
                                </td>
                                <td>
                                    <a href="">{{ item.product.title }}</a>
                                </td>
                                <td>
                                    {{ item.quantity }}

                                    <a href="?change_quantity={{ item.id }}&quantity=-1">-</a>
                                    <a href="?change_quantity={{ item.id }}&quantity=1">+</a>
                                </td>
                                <td>${{ item.total_price }}</td>
                                <td><a href="?remove_from_cart={{ item.id }}" class="delete">Remove</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td></td>
                            <td><strong>Total cost</strong></td>
                            <td><strong>{{ cart|length}}</strong></td>
                            <td colspan="2"><strong>${{ cart.get_total_price }}</strong></td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
         <div class="checkout_btn_inner float-right mb-6">
            <a href="{% url 'home' %}" class="button is-link is-outlined is-rounded">
            Continue Shopping
            </a>
            <a href="{% url 'order:checkout' %}" class="button is-primary is-rounded">
            Proceed to checkout
            </a>
          </div>
        </div>
        </div>
    {% else %}
        <div class="container mt-5 pt-5">
            <div class="notification is-danger">
                <button class="delete"></button>
                <p class="text-white">Your cart is empty!<a class="is-underlined" href="{% url 'home' %}">Shopping</a></p>
            </div>
        </div>
    {% endif %}
<!--================End Cart Area =================-->
{% endblock body %}