Project/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('secret/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('vendor/', include('vendor.urls')),
    path('customer/', include('customers.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('order/', include('order.urls')),
    path('review/', include('review.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

blog/urls.py
from django.urls import path
from . views import blog_post_view, blog_details_view, create_comment_view, blog_search_view

app_name = 'blog'

urlpatterns = [
    path('', blog_post_view, name='blog_view'),
    path('<slug:slug>', blog_details_view, name='blog_detail'),
    path('<slug:slug>/', create_comment_view, name='create_comment'),
    path('search/', blog_search_view, name='search'),
    # path('<slug:slug>/<int:pk>/delete', comment_delete_view, name='comment_delete'),
]

blog/models.py
from autoslug import AutoSlugField
from cloudinary.models import CloudinaryField
from taggit.managers import TaggableManager

from customers.models import Customer, User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from model.common_fields import BaseModel


class Category(models.Model):
    ''' Category for published posts. '''
    name = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='name', unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Post(BaseModel):
    ''' Represents a post in the blog application. '''
    class PublishedManager(models.Manager):
        ''' Custom manager for published posts. '''

        def get_queryset(self):
            return super().get_queryset().filter(status="published")

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    objects = models.Manager()  # The default manager
    published = PublishedManager()  # Custom manager

    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='title')
    content = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    is_published = models.BooleanField(default=False)
    image = CloudinaryField('image')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    tags = TaggableManager()

    class Meta:
        verbose_name_plural = 'Blogs'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:blog_detail", args=[self.slug])


class Comment(models.Model):
    ''' Represents comment on a post. '''
    body = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return f'Comment by {self.customer.full_name} on - {self.post.title}'

blog/forms.py
from django import forms
from blog.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

blog/views.py
import urllib.parse

from customers.decorators import customer_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm
from .models import Category, Comment, Post


@customer_required
@cache_page(60 * 2)
def blog_post_view(request):
    '''
    This view will render all posts & filter categories.
    '''
    posts = Post.published.all()
    paginator = Paginator(posts, 1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    category = request.GET.get('category')
    if category is None:
        posts = Post.published.all()
    else:
        posts = Post.published.filter(category__name=category)

    category = Category.objects.all()
    context = {
        'categories': category,
        'page_obj': page_obj,
    }
    return render(request, 'blog/blog.html', context)


@customer_required
@cache_page(60 * 2)
def blog_details_view(request, slug):
    '''
    This blog details will show more info about a specific blog post.
    '''
    post = get_object_or_404(Post, slug=slug)
    '''
    This will decode the post title for share article link.
    '''
    share_able_link = urllib.parse.quote(post.title)
    '''
    This will display the total comments of specific post.
    '''
    total_comments = Comment.objects.filter(post=post).count()
    '''
    This will display the total category number of the post.
    '''
    total_category = Category.objects.filter(post=post).count()
    '''
    This will display specific category of the post.
    '''
    category = Category.objects.filter(post=post)
    '''
    This will display who commented on the post.
    '''
    comments = Comment.objects.filter(post=post, customer=request.user.customer)

    context = {
        'post': post,
        'comments': comments,
        'total_category': total_category,
        'share_able_link': share_able_link,
        'total_comments_on_post': total_comments,
        'category': category.values_list('name', flat=True).first(),
    }

    return render(request, 'blog/blog_detail.html', context)


@customer_required
def create_comment_view(request, slug):
    '''
    This will create new comment on a specific post.
    '''
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = get_object_or_404(Post, slug=slug)
            comment.customer = request.user.customer
            comment.body = request.POST.get('body')
            comment.save()
            return redirect('blog:blog_detail', slug=slug)
    else:
        return render(request, 'blog/blog_detail.html')


@customer_required
@cache_page(60 * 2)
def blog_search_view(request):
    '''
    This view will search for the blog post with title, slug and category.
    '''
    queryset = request.GET.get('q')
    if queryset:
        posts = Post.published.filter(Q(title__icontains=queryset) | Q(slug__icontains=queryset) | Q(category__name=queryset))
        context = {
            'query': queryset,
            'page_obj': posts,
        }
        return render(request, 'blog/blog.html', context)
    else:
        raise Http404


# @customer_required
# def comment_delete_view(request, slug, pk):
#     '''
#     This will delete the comment.
#     '''
#     comment = get_object_or_404(Comment, pk=pk)
#     if request.method == 'POST':
#         comment.delete()
#         return redirect('blog:blog_detail', slug=slug)

blog/templates/blog/blog.html
{% extends 'core/_base.html' %}
{% block title %}Blog {% endblock %}
{% load static %}
{% load humanize %}
{% block body %}
<link href="https://cdn.jsdelivr.net/npm/tailwindcss/dist/tailwind.min.css" rel="stylesheet">
    <!-- slider Area Start-->
    <div class="slider-area ">
        <!-- Mobile Menu -->
        <div class="single-slider slider-height2 d-flex align-items-center" data-background="{% static 'assets/img/hero/category.jpg' %}">
            <div class="container">
                <div class="row">
                    <div class="col-xl-12">
                        <div class="hero-cap text-center">
                            <h2>Blog</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- slider Area End-->

    <!--================Blog Area =================-->
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">
                        {% for post in page_obj %}
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{{ post.image.url }}" alt="">
                                <a href="#" class="blog_item_date">
                                    <h3>{% now "d" %}</h3>
                                    <p>{% now "M" %}</p>
                                </a>
                            </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{{ post.get_absolute_url }}">
                                    <h2>{{ post.title }}</h2>
                                </a>
                                <p>{{ post.content |truncatechars:150 }}</p>
                                <ul class="blog-info-link">
                                    <li><a href="#"><i class="fa fa-user"></i>{{ post.tags.all.first | title }}</a></li>
                                </ul>
                            </div>
                        </article>

                       
                        {% empty %}
                        <div class="container content-center mx-auto mt-15">
                            <h1 class="font-bold p-10 text-center text-red-500">
                            Your search - "{{ query }}" Didn't match any  keyword. Please try again with different keywords.</h1>   
                        </div>
                        {% endfor %}
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-end">
                            {% if page_obj.has_previous %}
                                <a class="page-link" href="?page=1">&laquo; First</a>
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                            {% endif %}

                            {% if page_obj.has_next %}
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a>
                            {% endif %}
                            <li class="page-item"><a class="page-link" href="#"> 
                            {{ page_obj.number }}</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
                            {{ page_obj.paginator.num_pages }}</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget search_widget">
                            <form action="{% url 'blog:search' %}" method="GET">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <input name='q' type="text" class="form-control" placeholder='Search Keyword'
                                            onfocus="this.placeholder = ''"
                                            onblur="this.placeholder = 'Search Keyword'">
                                        <div class="input-group-append">
                                            <button class="btns" type="button"><i class="ti-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                    type="submit">Search</button>
                            </form>
                        </aside>
    
                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Category</h4>
                            <ul class="list cat-list">
                                {% for category in categories %}
                                <li>
                                    <a href="{% url 'blog:blog_view' %}?category={{category.name}}" class="d-flex">
                                        <p>{{category.name | title}}</p>
                                    </a>
                                </li>
                                {% endfor %}
                            </ul>
                        </aside>

                        <aside class="single_sidebar_widget popular_post_widget">

                            <h3 class="widget_title">Recent Post</h3>
                            <div class="media post_item">
                                <img src="{% static 'assets/img/post/post_1.png' %}" alt="post">
                                <div class="media-body">
                                    <a href="single-blog.html">
                                        <h3>From life was you fish...</h3>
                                    </a>
                                    <p>January 12, 2019</p>
                                </div>
                            </div>
                        </aside>

                        <aside class="single_sidebar_widget newsletter_widget">
                            <h4 class="widget_title">Newsletter</h4>

                            <form action="#">
                                <div class="form-group">
                                    <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                    type="submit">Subscribe</button>
                            </form>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->
{% endblock body %}

blog/templates/blog/blog_detail.html
{% extends 'core/_base.html' %}
{% block title %}Blog Details {% endblock %}
{% load static %}
{% load humanize %}
{% block body %}
    <!-- slider Area Start-->
    <div class="slider-area ">
      <!-- Mobile Menu -->
      <div class="single-slider slider-height2 d-flex align-items-center" data-background="{% static 'assets/img/hero/category.jpg' %}">
          <div class="container">
              <div class="row">
                  <div class="col-xl-12">
                      <div class="hero-cap text-center">
                          <h2>Details</h2>
                      </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- slider Area End-->
     
   <!--================Blog Area =================-->
   <section class="blog_area single-post-area section-padding">
      <div class="container">
         <div class="row">
            <div class="col-lg-8 posts-list">
               <div class="single-post">
                  <div class="feature-img">
                     <img class="img-fluid" src="{{ post.image.url }}" alt="">
                  </div>
                  <div class="blog_details">
                     <h2>{{ post.title }}</h2>
                     <ul class="blog-info-link mt-3 mb-4">
                        <li><a href="#"><i class="fa fa-user"></i> {{ post.tags.all.first | title }}</a></li>
                        <li><a href="#"><i class="fa fa-comments"></i> {{total_comments_on_post}} Comments</a></li>
                     </ul>
                     <p class="excert">
                        {{post.content}}
                     </p>
                    
                  </div>
               </div>
               <div class="navigation-top">
                  <div class="d-sm-flex justify-content-between text-center">
                     <div class="col-sm-4 text-center my-2 my-sm-0">
    
                     </div>
                     <ul class="social-icons">
                        <li><a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="https://twitter.com/home?{{share_able_link}}%20{{request.build_absolute_uri}}">
                        <i class="fab fa-twitter"></i></a></li>
                        <li><a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{share_able_link}}&summary={{post.content}}&source={{request.build_absolute_uri}}/"><i class="fab fa-linkedin"></i></a></li>
                        <li><a href="http://www.reddit.com/submit?url={{request.build_absolute_uri}}/&title={{share_able_link}}"><i class="fab fa-reddit"></i></a></li>
                     </ul>
                  </div>
               </div>
               <div class="comments-area">
                  <h4>{{total_comments_on_post}}  Comments</h4>
                  {% for comment in comments %}
                  <div class="comment-list">
                     <div class="single-comment justify-content-between d-flex">
                        <div class="user justify-content-between d-flex">
                           <div class="thumb">
                              <img src="{{ comment.customer.image.url }}" alt="{{ comment.customer.full_name }}">
                           </div>
                           <div class="desc">
                              <p class="comment">
                                 {{ comment.body }}
                              </p>
                              <div class="d-flex justify-content-between">
                                 <div class="d-flex align-items-center">
                                    <h5>
                                       <p>{{ comment.customer.full_name }}</p>
                                    </h5>
                                    <p class="date">{{ comment.created_at | naturaltime }}</p>
                                 </div>
                                 <div class="reply-btn">
                                    <a href="#" class="btn-reply text-uppercase">reply</a>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
                  {% endfor %}
               </div>
               <div class="comment-form">
                  <form 
                     action="{% url 'blog:create_comment' post.slug %}" 
                     method="POST" 
                     class="form-contact comment_form"
                     id="commentForm">
                     {% csrf_token %}
                     <div class="row">
                        <div class="col-12">
                           <div class="form-group">
                              <textarea class="form-control w-100" name="body" id="comment" cols="30" rows="9"
                                 placeholder="Write Comment"></textarea>
                           </div>
                        </div>
                     </div> 
      
                     <div class="form-group">
                        <button type="submit" class="button button-contactForm btn_1 boxed-btn">Submit</button>
                     </div>
                  </form>
               </div>
            </div>
            <div class="col-lg-4">
               <div class="blog_right_sidebar">
                  <aside class="single_sidebar_widget post_category_widget">
                     <h4 class="widget_title">Category</h4>
                     <ul class="list cat-list">
                        <li>
                           <a href="#" class="d-flex">
                              <p>{{category}}</p>
                              <p>({{total_category}})</p>
                           </a>
                        </li>
                     </ul>
                  </aside>
                  <aside class="single_sidebar_widget newsletter_widget">
                     <h4 class="widget_title">Newsletter</h4>
                     <form action="#">
                        <div class="form-group">
                           <input type="email" class="form-control" onfocus="this.placeholder = ''"
                              onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
                        </div>
                        <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                           type="submit">Subscribe</button>
                     </form>
                  </aside>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!--================ Blog Area end =================-->
{% endblock body %}
  