Project/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('secret/', admin.site.urls),
    path('', include('core.urls')),
    path('blog/', include('blog.urls')),
    path('vendor/', include('vendor.urls')),
    path('customer/', include('customers.urls')),
    path('product/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('wishlist/', include('wishlist.urls')),
    path('order/', include('order.urls')),
    path('review/', include('review.urls')),
    path('newsletter/', include('newsletter.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

blog/urls.py
from django.urls import path
from . views import blog_post_view, blog_details_view, create_comment_view, blog_search_view

app_name = 'blog'

urlpatterns = [
    path('', blog_post_view, name='blog_view'),
    path('<slug:slug>', blog_details_view, name='blog_detail'),
    path('<slug:slug>/', create_comment_view, name='create_comment'),
    path('search/', blog_search_view, name='search'),
    # path('<slug:slug>/<int:pk>/delete', comment_delete_view, name='comment_delete'),
]

customers/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('new', views.CustomerSignUpView, name='customer_sign_up'),
    path('sign-in', views.SignInView.as_view(), name='customer_sign_in'),
    path(
        "sign-out/",
        auth_views.LogoutView.as_view(template_name="customer/logout.html"),
        name="customer_sign_out",
    ),
    path('profile/', views.CustomerProfile, name='customer_profile'),
    path('change/password/', views.change_password_view, name='change_password'),
    path('profile/update/', views.CustomerProfileUpdate, name='customer_profile_update'),


    path('wishlist/followed/store/', views.customerWishlistAndFollowedStore, name='customer_wishlist_and_followed_store'),

]

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
    path('checkout', views.checkout, name='checkout'),
    path('confirmation', views.order_complete, name='order_complete'),
    path('returns', views.customerReturns, name='customer_returns'),
    path('cancellation', views.customerCancellations, name='customer_cancellation'),
    path('history', views.customerOrderHistory, name='customer_order_history'),
    path('view/<int:order_id>', views.order_details, name='order_details'),
]

customers/models.py
from cloudinary.models import CloudinaryField
from django_countries.fields import CountryField

from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models
from model.common_fields import BaseModel

from .manager import UserManager


class User(AbstractUser):
    """ Custome User model"""

    username = None
    email = models.EmailField(unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    is_customer = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)

    objects = UserManager()


class Customer(BaseModel):
    """Customer model for storing customer information"""

    user = models.OneToOneField(
        User, related_name='customer', on_delete=models.CASCADE)
    full_name = models.CharField(max_length=255)
    image = CloudinaryField('avatar', null=True, blank=True)
    email = models.EmailField()
    phone_regex = RegexValidator(
        regex=r'^\+?880?\d{9,11}$', message="Phone number must be entered in the format: '+8801234233566'. Up to 11 digits allowed.")
    phone_number = models.CharField(
        validators=[phone_regex], max_length=17, blank=True)
    address = models.CharField(max_length=255)
    country = CountryField()

    def __str__(self):
        return self.full_name

    @property
    def get_user_full_name(self):
        """Returns the first_name plus the last_name, with a space in between."""
        full_name = f"{self.full_name}"
        return full_name.strip()

    class Meta:
        verbose_name_plural = "Customer"

customers/forms.py
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Checkbox
from django_countries.fields import CountryField

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms import ModelForm

from .models import Customer, User


class CustomerSignUpForm(UserCreationForm):
    country = CountryField(
        blank_label='(Select country)',).formfield(null=True)
    address = forms.CharField(widget=forms.Textarea)
    full_name = forms.CharField(max_length=255)
    phone_number = forms.CharField(max_length=17)
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox)

    def __init__(self, *args, **kwargs):
        super(CustomerSignUpForm, self).__init__(*args, **kwargs)

        for fieldname in ["password1", "password2"]:
            self.fields[fieldname].help_text = None

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('full_name',
                  'email', 'phone_number', 'country', 'address', 'password1', 'password2')

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_customer = True
        user.save()
        customer = Customer.objects.create(user=user)
        customer.email = self.cleaned_data.get('email')
        customer.country = self.cleaned_data.get('country')
        customer.address = self.cleaned_data.get('address')
        customer.full_name = self.cleaned_data.get('full_name')
        customer.phone_number = self.cleaned_data.get('phone_number')
        customer.save()

        return customer


class CustomerUpdateForm(ModelForm):
    class Meta:
        model = Customer
        fields = ('full_name', 'email', 'image', 'phone_number', 'country', 'address')

customers/views.py
from django.contrib import messages
from django.contrib.auth import (
    authenticate, login, update_session_auth_hash, views as auth_views,
)
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.shortcuts import redirect, render
from order.models import OrderItem

from .decorators import customer_required
from .forms import CustomerSignUpForm, CustomerUpdateForm
from .utils import service


@customer_required
def customerWishlistAndFollowedStore(request):
    ''' customer wishlist and followed store.'''
    return render(request, 'customer/wishlist_and_followed_store.html')


@customer_required
def CustomerProfile(request):
    ''' customer profile '''

    order = OrderItem.objects.filter(order__customer=request.user.customer)

    context = {
        'customer': request.user.customer,
        'orders': order,
    }

    return render(request, 'customer/customer_profile.html', context)


@customer_required
def CustomerProfileUpdate(request):
    ''' Update customer profile '''
    if request.method == 'POST':
        form = CustomerUpdateForm(request.POST, request.FILES, instance=request.user.customer)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile was successfully updated!')
            return redirect('customer_profile')
    else:
        form = CustomerUpdateForm(instance=request.user.customer)
        context = {
            'form': form,
        }
        return render(request, 'customer/customer_profile_edit.html', context)


def CustomerSignUpView(request):
    ''' Sign up view for new customer account.'''
    if request.method == 'POST':
        form = CustomerSignUpForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thanks for registering. You are now logged in.')
            user = authenticate(email=form.cleaned_data['email'], password=form.cleaned_data['password1'])
            login(request, user)
            service.send_welcome_mail(request, request.user.customer.email)
            return redirect('/')
        else:
            messages.error(request, 'Invalid form.')
    else:
        form = CustomerSignUpForm()
        return render(request, 'customer/sign_up.html', {'form': form})


@customer_required
def change_password_view(request):
    '''A form for allowing customer to change with old password '''
    if request.method == "POST":
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, "Password Change Successfully!")
            return redirect('/')
    else:
        form = PasswordChangeForm(user=request.user)
        return render(request, "customer/password_change.html", {"form": form})


class SignInView(auth_views.LoginView):
    ''' Sign in for customer '''
    form_class = AuthenticationForm
    template_name = 'customer/sign_in.html'

customers/templates/customer/customer_profile.html
{% extends 'core/_base.html' %} 
{% block title %}Manage My Account {% endblock %}
{% load static %} 
{% block body %}
<link
  href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
  rel="stylesheet"
/>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"
/>

<section class="bg-white">
  <div class="container mx-auto flex items-center flex-wrap pt-4 pb-12">
    <nav id="store" class="w-full z-30 top-0 px-6 py-1">
      <div
        class="
          w-full
          container
          mx-auto
          flex flex-wrap
          items-center
          justify-between
          mt-0
          px-2
          py-3
        "
      >
        <nav class="breadcrumb is-small bg-white has-succeeds-separator" aria-label="breadcrumbs">
          <ul>
            <li><a href="{% url 'customer_profile' %}">My Profile</a></li>
            <li><a href="{% url 'order:customer_order_history' %}">My Orders</a></li>
            <li><a href="{% url 'customer_review_history' %}">My Reviews</a></li>
            <li><a href="{% url 'customer_wishlist_and_followed_store' %}">My Wishlist & Followed Stores</a>
            </li>
          </ul>
        </nav>
        </a>
          <h3 class="is-size-4 font-extrabold md:text-lg has-text-left-mobile has-text-left">Manage My Account</h3>
      </div>
    </nav>
    {% if messages %} 
      {% for message in messages %}
      <div class="notification is-success is-toast">{{ message }}</div>
      {% endfor %} 
    {% endif %}

    <div class="card-content">
        <div class="media">
          <div class="media-left">
            <div class="relative w-24 h-24">
              <img class="rounded-full border border-gray-100 shadow-sm" src="{{ customer.image.url }}" alt="{{customer.full_name}}" />
              <div class="absolute top-0 right-0 h-6 w-6 my-1 border-4 border-white rounded-full bg-green-400 z-2"></div>
            </div>
            </div>
            <div class="media-content">
              <p class="title is-4">{{customer.full_name}}</p>
              <p class="subtitle is-6">{{customer.email}}</p>
              <hr>
              <h3 class="font-extrabold md:text-lg">Shipping Address</h3>
              <p class="subtitle is-size-6 mt-2">{{customer.address}} - {{customer.country.name}}
              <br>{{customer.phone_number}}</p>

              <a  href="{% url 'customer_profile_update'%}" class="button is-dark is-small no-underline hover:no-underline">Edit</a>
            </div>
          </div>
        </div>
        <div class="container">
        <h3 class="font-extrabold md:text-lg">Recent Orders</h3>
        <table class="table has-text-centered">
          <tr class="th">
          {% for item in orders %}
              <th>Order #</th>
              <th>Status</th>
              <th>Placed On</th>
              <th>Items</th>
              <th>Total</th>
              <th></th>
          </tr>
       
                   
          <tr>
              <td>{{ forloop.counter }}</td>
              <td>{{ item.order.status }}</td>
              <td>{{ item.order.delivered_date }}</td>
              <td>
              {% if item.product.image %}
              <figure class="container-fluid image is-96x96">
                <img src="{{ item.product.image.url }}">
              </figure> 
              {% else %}
              <figure class="container-fluid image is-96x96">
                <img src="{{ item.product.url }}">
              </figure>
              {% endif %}
              </td>
              <td>৳{{ item.product.price }}</td>
              <td class="pt-5"><a href="{% url 'order:order_details' item.id %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full">MANAGE</a></td>
          </tr>
       
          {% endfor %}
        </table>
      </div>
    </div>
    </div>
  </div>
</section>


    {% block footer %}
        {% include 'core/footer.html' %}
    {% endblock footer %}

{% endblock body %}

customers/templates/customer/customer_profile_edit.html
{% extends 'core/_base.html' %} 
{% block title %}Manage My Account {% endblock %}
{% load static %} 
{% load crispy_forms_tags %}
{% block body %}
<link
  href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
  rel="stylesheet"
/>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"
/>

<section class="bg-white">
  <div class="container mx-auto flex items-center flex-wrap pt-4 pb-12">
    <nav id="store" class="w-full z-30 top-0 px-6">
      <div
        class="
          w-full
          container
          flex flex-wrap
          items-center
          justify-between
        "
      >
        <nav class="breadcrumb is-small bg-white" aria-label="breadcrumbs">
          <ul>
            <li><a href="">Unsubscribe to our Newsletter</a></li>
          </ul>
        </nav>
      </div>
    </nav>
    <style>
        #div_id_address {
            margin-top: 2rem;
            padding-top: 1rem;
        }
    </style>
    {% if messages %} 
      {% for message in messages %}
      <button class="delete"></button>
      <div class="notification is-success is-toast">{{ message }}</div>
      {% endfor %} 
    {% endif %}
    <div class="w-full lg:w-1/2 p-6">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="button is-link">Update</button>
            <a  href="{% url 'change_password'%}" class="button is-dark no-underline hover:no-underline">Change Password</a>
        </form>
    </div>
  </div>
</section>
{% endblock body %}

customers/templates/customer/logout.html
<div class="col-md-8 pt-5 mt-5 text-2xl">
   <div class="mb-4 my-6 mt-5">
    <h1 class='text-success font-weight-bold'>
    Thanks for spending some quality time with Photo Album. <br>
    <hr>
    <a href="{% url 'customer_sign_in' %}" class='text-primary'>Login back in here </strong> </h1>
    </div>
</div>

customers/templates/customer/password_change.html
{% extends 'core/_base.html' %} 
{% block title %}Change Password {% endblock %}
{% load static %} 
{% load crispy_forms_tags %}
{% block body %}
<link
  href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
  rel="stylesheet"
/>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"
/>

<section class="bg-white">
  <div class="container mx-auto flex items-center flex-wrap pt-4 pb-12">
    <style>
        #div_id_address {
            margin-top: 2rem;
            padding-top: 1rem;
        }
    </style>
    {% if messages %} 
      {% for message in messages %}
      <button class="delete"></button>
      <div class="notification is-success is-toast">{{ message }}</div>
      {% endfor %} 
    {% endif %}
    <div class="w-full lg:w-1/2 p-6">
        <form method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="button is-link">Change Password</button>
        </form>
    </div>
  </div>
</section>
{% endblock body %}

customers/templates/customer/sign_in.html
{% extends 'core/_base.html' %}
{% block title %}Sign in {% endblock %}
{% load static %}
{% load crispy_forms_tags %}
{% block body %}
<!-- slider Area Start-->
<div class="slider-area ">
    <!-- Mobile Menu -->
    <div class="single-slider slider-height2 d-flex align-items-center" data-background="{% static 'assets/img/hero/category.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>Sign In</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- slider Area End-->

<!--================Signed in Area =================-->
<section class="login_part section_padding ">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-6 col-md-6">
                <div class="login_part_text text-center">
                    <div class="login_part_text_iner">
                        <h2>New to our Shop?</h2>
                        <p>There are advances being made in science and technology
                            everyday, and a good example of this is the</p>
                        <a href="{% url 'customer_sign_up' %}" class="btn_3">Create an Account</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="login_part_form">
                    <div class="login_part_form_iner">
                        <h3>Welcome Back ! <br>
                            Please Sign in now</h3>
                        <form class="row contact_form" action="#" method="post">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <div class="col-md-12 form-group">
                                <div class="creat_account d-flex align-items-center">
                                    <input type="checkbox" id="f-option" name="selector">
                                    <label for="f-option">Remember me</label>
                                </div>
                                <button type="submit" value="submit" class="btn_3">
                                    log in
                                </button>
                                <a class="lost_pass" href="#">forget password?</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock body %}

customers/templates/customer/sign_up.html
{% extends 'core/_base.html' %} 
{% block title %}Sign Up{% endblock %}
{% load static %} 
{% load tailwind_filters %}
{% block body %}
<link
  href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
  rel="stylesheet"
/>
<!-- slider Area Start-->
<div class="slider-area">
  <!-- Mobile Menu -->
  <div
    class="single-slider slider-height2 d-flex align-items-center"
    data-background="{% static 'assets/img/hero/category.jpg' %}"
  >
    <div class="container">
      <div class="row">
        <div class="col-xl-12">
          <div class="hero-cap text-center">
            <h2>Sign Up</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- slider Area End-->
{% if messages %} 
  {% for message in messages %}
  <div class="notification is-success is-toast">{{ message }}</div>
  {% endfor %} 
{% endif %}
<!--================Signed up Area Start=================-->
<section class="login_part section_padding">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 col-md-6">
        <div class="login_part_text text-center">
          <div class="login_part_text_iner">
            <h2>New to our Shop?</h2>
            <p>
              There are advances being made in science and technology everyday,
              and a good example of this is the
            </p>
            <a href="{% url 'customer_sign_up' %}" class="btn_3"
              >Create an Account</a
            >
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-md-6">
        <div class="login_part_form">
          <div class="login_part_form_iner">
            <h3>Welcome!<br />Please Sign Up now</h3>
            <form action="#" method="POST">
              {% csrf_token %}
              {{ form|crispy }}
              <div class="col-md-12 form-group">
                <div class="creat_account d-flex align-items-center">
                  <input type="checkbox" id="f-option" name="selector" />
                  <label for="f-option">Remember me</label>
                </div>
                <button type="submit" value="submit" class="btn_3">
                  Sign Up
                </button>
                <a class="lost_pass" href="#">forget password?</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--================Signed up Area End=================-->
{% endblock body %}

customers/templates/customer/wishlist_and_followed_store.html
{% extends 'core/_base.html' %} 
{% block title %}Manage My Wishlists {% endblock %}
{% load static %} 
{% block body %}
<link
  href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
  rel="stylesheet"
/>
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"
/>

<section class="bg-white">
  <div class="container mx-auto flex items-center flex-wrap pt-4 pb-12">
    <nav id="store" class="w-full z-30 top-0 px-6 py-1">
      <div
        class="
          w-full
          container
          mx-auto
          flex flex-wrap
          items-center
          justify-between
          mt-0
          px-2
          py-3
        "
      >
        <nav class="breadcrumb is-small bg-white" aria-label="breadcrumbs">
          <ul>
            <li><a href="{% url 'customer_profile' %}">My Profile</a></li>
            <li><a href="{% url 'order:customer_order_history' %}">My Orders</a></li>
            <li><a href="{% url 'order:customer_returns' %}">My Returns</a></li>
            <li><a href="{% url 'order:customer_cancellation' %}">My Cancellations</a></li>
            <li><a href="{% url 'customer_wishlist_and_followed_store' %}">My Wishlist & Followed Stores</a>
            </li>
          </ul>
        </nav>
          <h3 class="is-size-4 has-text-weight-medium has-text-left-mobile has-text-left">Manage My Account</h3>
      </div>
    </nav>
    {% if messages %} 
      {% for message in messages %}
      <div class="notification is-success is-toast">{{ message }}</div>
      {% endfor %} 
    {% endif %}

    <div class="card-content">
        <div class="container">
        <h3 class="is-size-4 has-text-weight-medium">My Orders</h3>
        <table class="table has-text-centered">
          <tr class="th">
          {% for item in order_items %}
              <th>Order No.</th>
              <th>Thumbnail</th>
              <th>Product</th>
              <th>Quantity</th>
              <th>Price</th>
          </tr>
       
                   
          <tr>
              <td>{{item.id}}</td>
              <td>
               <figure class="container-fluid image is-96x96">
                <img src="{{item.product_image.url}}">
              </figure> 
              </td>
              <td>{{item.product_title|title}}</td>
              <td>{{item.product_quantity}}</td>
              <td>{{item.product_price}}</td>
          </tr>
       
    
          {% endfor %}
        </table>
      </div>
    </div>
    </div>
  </div>
</section>
{% endblock body %}